name: build on change

on:
  #push:
    #branches:
     # - master
  workflow_dispatch:
  #repository_dispatch:
   #types: debian

jobs:
  debian:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: docker login
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: treehouses debian
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          repo="treehouses/debian"
          source .github/workflows/utils.sh
          echo "amd64"
          debian_x86_sha=$(get_variant_sha "debian" "latest" "amd64")
          echo $debian_x86_sha
          variant_debian_x86_sha=$(get_manifest_sha "$repo:latest" "amd64")
          echo $variant_debian_x86_sha
          echo "arm"
          balena_rpi_sha=$(get_tag_sha "balenalib/raspberry-pi-debian" "latest")
          echo $balena_rpi_sha
          variant_rpi_sha=$(get_manifest_sha "$repo:latest" "arm")
          echo $variant_rpi_sha
          echo "arm64"
          debian_arm64_sha=$(get_variant_sha "debian" "latest" "arm64")
          echo $debian_arm64_sha
          variant_debian_arm64_sha=$(get_manifest_sha "$repo:latest" "arm64")
          echo $variant_debian_arm64_sha
          echo "change"
          flag=$(compare_sha  "$debian_x86_sha" "$variant_debian_x86_sha" "$balena_rpi_sha" "$variant_rpi_sha" "$debian_arm64_sha" "$variant_debian_arm64_sha")
          echo $flag
          if [[ $flag == true ]]; then
            tag="$(date +%Y%m%d%H%M)"
            echo $tag
            docker manifest create $repo:$tag "debian@"$debian_x86_sha "balenalib/raspberry-pi-debian@"$balena_rpi_sha "debian@"$debian_arm64_sha
            docker manifest annotate $repo:$tag "debian@"$debian_arm64_sha --arch arm64
            docker manifest annotate $repo:$tag "balenalib/raspberry-pi-debian@"$balena_rpi_sha --arch arm
            docker manifest inspect $repo:$tag
            docker manifest push $repo:$tag
            tag2="latest"
            echo $tag2
            docker manifest create $repo:$tag2 "debian@"$debian_x86_sha "balenalib/raspberry-pi-debian@"$balena_rpi_sha "debian@"$debian_arm64_sha
            docker manifest annotate $repo:$tag2 "debian@"$debian_arm64_sha --arch arm64
            docker manifest annotate $repo:$tag2 "balenalib/raspberry-pi-debian@"$balena_rpi_sha --arch arm
            docker manifest inspect $repo:$tag2
            docker manifest push $repo:$tag2 
            echo "https://hub.docker.com/r/treehouses/alpine/tags"
          else
            echo "no changes"
          fi
